#!/usr/bin/env python2
import sys

HEADER = """! RI-MP2 RIJK def2-TZVP def2-TZVP/C def2-TZVP/JK TIGHTSCF
% maxcore 2000
% mp2 density relaxed end"""

if __name__ == "__main__":

    xyz_file = open(sys.argv[1])
    lines = xyz_file.readlines()
    xyz_file.close()

    charge = 0 
    
    if "charge = " in lines[1]:
        tokens = lines[1].split()
        charge = float(tokens[2])

    print HEADER

    print "*xyz %i 1" % charge

    for i, line in enumerate(lines[2:]):
    
        tokens = line.split()
    
        print " %-4s %16.10f %16.10f %16.10f " % \
            (tokens[0], float(tokens[1]),  float(tokens[2]), float(tokens[3]))

    print "*"
